version : 2

sources:
  - name : jaffle_shop
    database : raw
    schema :  jaffle_shop
    tables : 
      - name : customers
      - name : orders

  - name : stripe
    database : raw
    schema : stripe
    tables :
      - name : payment

models :
  - name : stg_customers
    columns :
      - name : customer_id
        tests:
          - unique
          - not_null

  - name : stg_orders
    columns :
      - name : order_id
        tests:
          - unique
          - not_null
      - name : status
        tests :
          - accepted_values :
              values : 
                - completed
                - shipped
                - returned
                - return_pending
                - placed
      - name : customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id